# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
pr: none

resources:
  repositories:
    - repository: templates
      endpoint: g3rv4
      type: github
      name: g3rv4/AzurePipelinesTemplates

stages:
- template: agent-provision.yml@templates
- stage: Build
  pool: default
  jobs:
  - job: Build
    workspace:
      clean: all
    steps:
    - powershell: |
        $hash = '$(Build.SourceVersion)'
        $buildId = '$(Build.BuildId)'
        $version = "$($hash.Substring(0, 7)).$buildId"

        Write-Host "##vso[build.updatebuildnumber]$($version)"

        $pwd = pwd
        $uid = sh -c 'id -u'
        $gid = sh -c 'id -g'

        docker run --rm -v "$($pwd):/var/src" mcr.microsoft.com/dotnet/core/sdk:3.0-alpine3.9 ash -c "dotnet build -c Release /var/src/GMeet.csproj && chown -R $($uid):$($gid) /var/src"
        if($LASTEXITCODE){
            Exit $LASTEXITCODE
        }
      failOnStderr: false
    - publish: 'bin/Release/netcoreapp3.0'
      artifact: 'GMeet.$(Build.BuildNumber)'
