name: Create Image
on:
  push:
    branches:
      - main

jobs:
  create-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # get entire git tree, required for nerdbank gitversioning
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push the Docker image
        shell: pwsh
        run: |
          Push-Location src
          $version = (nbgv get-version -f json | ConvertFrom-Json).SimpleVersion
          $version = "v$version"
          Pop-Location

          docker build . -t ghcr.io/g3rv4/gmeet:latest
          docker tag ghcr.io/g3rv4/gmeet:latest ghcr.io/g3rv4/gmeet:$version
          docker push ghcr.io/g3rv4/gmeet:latest
          docker push ghcr.io/g3rv4/gmeet:$version
