name: build
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: Azure/get-keyvault-secrets@v1.1
      with:
        keyvault: "ActionsBuild"
        secrets: 'OctopusServerUrl, OctopusApiKey'
      id: azureSecrets

    - name: Build project
      shell: pwsh
      run: ./build.ps1 $env:GITHUB_RUN_NUMBER $env:GITHUB_SHA
    - name: Push it to GitHub
      run: curl -X PUT -u "$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}" -F package=@$PKG_PATH https://nuget.pkg.github.com/g3rv4/
    - name: Create and deploy an Octopus release
      run: |
        dotnet tool install --global Octopus.DotNet.Cli
        dotnet-octo create-release --project gmeet --releaseNumber $VERSION --package gmeet:$VERSION_WITHOUT_HASH --deployto Dev --server "${{ steps.azureSecrets.outputs.OctopusServerUrl }}" --apiKey "${{ steps.azureSecrets.outputs.OctopusApiKey }}" --progress
